package src.services;

public class IdGenerationService {
    private int id;
    public IdGenerationService(int id){
        this.id=id;
    }

    // access file from ../../public/data/filename.json
    public int autoGeneratedId(String fileName){}
}